
name: Build Test
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout theme
        uses: actions/checkout@v4
        with:
          path: themes/robust

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.120.4'
          extended: true

      - name: Create new Hugo site
        run: hugo new site mysite

      - name: Copy theme to site
        run: |
          cp -r themes/robust mysite/themes/robust
      - name: Build
        run: |
          cd mysite
          hugo --theme robust --minify